<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.mycompany</groupId>
	<artifactId>sinistros-sapi-pfm</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>mule-application</packaging>
	<name>sinistros-sapi-pfm</name>
	<properties>
		<api.version>1.0.0</api.version>
		<mule.maven.plugin.version>4.3.0</mule.maven.plugin.version>
		<mule.http.connector.version>1.10.0</mule.http.connector.version>
		<mule.sockets.connector.version>1.2.4</mule.sockets.connector.version>
		<app.runtime>4.6.7</app.runtime>
		<maven.clean.plugin.version>3.2.0</maven.clean.plugin.version>
		<munit.version>3.3.1</munit.version>
		<munit.tools.version>3.3.1</munit.tools.version>
		<munit.runner.version>3.3.1</munit.runner.version>
		<munit.assertions.version>1.2.1</munit.assertions.version>
		<mule.opentelemetry.module.version>2.3.3-SNAPSHOT</mule.opentelemetry.module.version>
		<mule.tracing.module.version>1.1.0</mule.tracing.module.version>
		<secure.config.prop.module.version>1.2.7</secure.config.prop.module.version>
		<maven.resource.plugin.version>3.3.1</maven.resource.plugin.version>
		<json.logger.version>2.1.0</json.logger.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>0c8d88c2-d09d-472f-a589-9ca239060bdc</groupId>
			<artifactId>sinistros-sapi-pfm</artifactId>
			<version>1.0.1</version>
			<classifier>raml</classifier>
			<type>zip</type>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<version>1.2.4</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<version>1.11.0</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.weave</groupId>
			<artifactId>assertions</artifactId>
			<version>${munit.assertions.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<version>${munit.runner.version}</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<version>${munit.tools.version}</version>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<classifier>mule-plugin</classifier>
			<version>${secure.config.prop.module.version}</version>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<version>1.10.3</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-objectstore-connector</artifactId>
			<version>1.2.2</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.connectors</groupId>
			<artifactId>mule-kafka-connector</artifactId>
			<version>4.10.0</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-db-connector</artifactId>
			<version>1.14.17</version>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.30</version>
		</dependency>
	</dependencies>
	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>anypoint-exchange</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
		<repository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>mulesoft-releases</id>
			<name>MuleSoft Releases Repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
	<distributionManagement>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange v3</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
			<layout>default</layout>
		</repository>
	</distributionManagement>
</project>
