#  This property file contains environment agnostic properties

application:
  name: "architecture-eapi-template"
  version: "v1"

# API Spec Properties
api:
  spec: "resource::${businessUnity}:${project.name}:${api.version}:raml:zip:${project.name}.raml"
  majorVersion: "v1"